spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    root: WARN
    com.lunorion.labs: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

jwt:
  secret: dev-secret-key-not-for-production
  expiration: 86400000

server:
  port: 8080
