-- ============================================================
-- SEED DATA
-- ============================================================
-- Este archivo quedó intencionalmente vacío.
-- Los datos de prueba (tenant, usuarios demo, clientes, productos,
-- órdenes de trabajo, etc.) fueron eliminados.
--
-- Nota: el esquema de la base de datos se define en init.sql.
-- ============================================================
